highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Anthony Garvan's Resume
name: Anthony Garvan
email: email
email_full: mailto:anthony.garvan@gmail.com
website: anthonygarvan.com
website_full: http://www.anthonygarvan.com
github: anthonygarvan
twitter: anthonygarvan
tel: 203-435-8311
google_maps: 'https://www.google.com/maps/place/Chicago,+IL/@41.8339025,-88.0130394,10z/data=!3m1!4b1!4m2!3m1!1s0x880e2c3cd0f4cbed:0xafe0a6ad09c0c000'
city: Chicago
country: USA
google_analytics: UA-38185442-3

# needed for travis-ci build
exclude: [vendor]
